# Generated by Django 5.0.6 on 2025-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_salary_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='positions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
