# Generated by Django 5.0.6 on 2025-03-01 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='parentsstudents', to='core.student'),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
